### ISSUE TITLE
Update nginx updatecli manifest

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/docker-confluence-data#62]
As noted in:
- https://github.com/jenkins-infra/docker-confluence-data/issues/61#issuecomment-2104481484

> > The updatecli manifests with upper cases looks weird though
>
> Maybe due to the old "pullrequest" syntax used in the manifest?
> https://github.com/jenkins-infra/docker-confluence-data/blob/d8f5186e941cd6541ff3aa4a3b25c4bd064ac2ab/updatecli/updatecli.d/nginx.yaml#L56-L65

The updatecli manifest should be updated to replace the deprecated `pullrequests` section by an `actions` one:
https://www.updatecli.io/docs/plugins/actions/github/

This manifest should also update the tests file so it can test the correct version:
https://github.com/jenkins-infra/docker-confluence-data/blob/d8f5186e941cd6541ff3aa4a3b25c4bd064ac2ab/cst.yml#L3-L7

**Comment by dduportal** [comment]
Fixed by #63 and #65 

The Nginx version was upgraded with success after these PRs, in #64
